apicompany/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('projectapp.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')), # FOR GOOGLE SIGN IN #
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projectapp/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('logout/', logoutUser, name='logoutpage'),
    path('login/', loginUser, name='loginpage'),
    path('signup/', signupUser, name='signuppage'),
    path('sendmail/', sendmailUser, name='sendmailpage'),
    path('verify/<auth_token>', verify, name="verify"),
    path('error/', errorUser, name="errorpage"),
    path('', home, name='homepage'),
    path('contacts/', allcontacts, name='contactspage'),
    path('deals/', alldeals, name='dealspage'),
    path('test/', testpost, name='testpage'),
    path('forms/<str:form_pk>/', forms, name='formspage'),
    path('webhook/<str:form_pk>/', webhook, name='webhookpage'),
]

projectapp/models.py
from django.db import models
from django.contrib.auth.models import User

class EmailVerification(models.Model):
    user = models.CharField(max_length=30)
    auth_token = models.CharField(max_length=100, null=True, blank=True)
    is_verified = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user
    
class Company(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    webhook_url = models.CharField(max_length=200, null=True, blank=True)
    url = models.CharField(max_length=200, null=True, blank=True)
    apitoken = models.CharField(max_length=200, null=True, blank=True)
    baseurl = models.CharField(max_length=100, null=True, blank=True)
    userid = models.CharField(max_length=50, null=True, blank=True)

    def __str__(self):
        return str(self.user)

class Form(models.Model):
    reciever = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=50, null=True, blank=True)
    email = models.CharField(max_length=50, null=True, blank=True)
    deal = models.TextField(max_length=200, null=True, blank=True)
    note = models.TextField(max_length=200, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.reciever)
    
class Post_Data(models.Model):
    reciever = models.ForeignKey(User, on_delete=models.CASCADE)
    url = models.CharField(max_length=200, null=True, blank=True)
    data = models.CharField(max_length=200, null=True, blank=True)
    params = models.CharField(max_length=200, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.reciever)
    
class Contact(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=50, null=True, blank=True)
    email = models.CharField(max_length=50, null=True, blank=True)
    phone = models.CharField(max_length=50, null=True, blank=True)

    def __str__(self):
        return str(self.owner)
    
class Deal(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=50, null=True, blank=True)
    person = models.CharField(max_length=50, null=True, blank=True)
    value = models.IntegerField(default=1000, null=True, blank=True)

    def __str__(self):
        return str(self.owner)

projectapp/forms.py
from django.forms import ModelForm
from .models import *

class DealCreationForm(ModelForm):
    class Meta:
        model = Form
        fields = ['name', 'email', 'deal', 'note']

class CompanyForm(ModelForm):
    class Meta:
        model = Company
        fields = ['apitoken', 'baseurl', 'userid']

projectapp/views.py
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from apicompany.settings import DEBUG
from django.core.mail import send_mail
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.http import JsonResponse
from django.conf import settings as conf_settings
from django.urls import reverse
from .models import *
from .forms import *
import requests
import json
import uuid

def sendmailUser(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        user_obj = User.objects.filter(username=username).first()
        if not user_obj:
            auth_token = str(uuid.uuid4())
            profile_obj = EmailVerification.objects.create(user=username, auth_token=auth_token)
            profile_obj.save()
            send_mail_after_registration(username, auth_token)
            messages.info(request, 'Email has been sent to your mail address. Please verify your account to proceed.')
            return redirect('sendmailpage')
        else:
            messages.info(request, 'User already exists.')
            return redirect('sendmailpage')
    return render(request, 'projectapp/sendmailpage.html')

def signupUser(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        firstname = request.POST.get('first_name')
        lastname = request.POST.get('last_name')
        password1 = request.POST.get('password1')
        password2 = request.POST.get('password2')
        user_exist = User.objects.filter(username=username).first()
        if user_exist:
            messages.info(request, 'Username has already been taken.')
            return redirect('signuppage')
        elif password1 != password2:
            messages.info(request, 'Passwords did not match.')
            return redirect('signuppage')
        else:
            profile_obj = EmailVerification.objects.filter(user=username).first()
            if profile_obj:
                if profile_obj.is_verified:
                    user_obj = User.objects.create_user(username, first_name=firstname, last_name=lastname, password=password1)
                    url_token = str(uuid.uuid4())
                    company_obj = Company.objects.create(user=user_obj, url=url_token, webhook_url=url_token)
                    company_obj.save()
                    emailverifyform = EmailVerification.objects.filter(user=username).first()
                    emailverifyform.delete()
                    user = authenticate(username=username, password=password1)
                    login(request, user)
                    return redirect('homepage')
                else:
                    auth_token = str(uuid.uuid4())
                    profile_obj.auth_token = auth_token
                    profile_obj.save()
                    email_obj = User.objects.get(username=username).username
                    send_mail_after_registration(email_obj, auth_token)
                    messages.info(request, 'Your account is not verified. Please check your mailbox for "Account Verification" mail and click on the link to verify your account. We have sent a new "Account Verification" mail.')
            else:
                messages.info(request, 'You need to provide your mail address for account verification before you sign up.')
                return redirect('sendmailpage')
    return render(request, 'projectapp/signuppg.html')

def send_mail_after_registration(email, token):
    if DEBUG:
        link = '127.0.0.1:8000'
    else:
        link = 'https://yusuffrazofficial001.pythonanywhere.com/'
    subject = 'Account Verification'
    message = f'Hi {email}, please click on the link to verify your account on Desi Digilocker. {link}/verify/{token}'
    email_from = conf_settings.EMAIL_HOST_USER
    recipient_list = [email]
    send_mail(subject, message, email_from, recipient_list)

def verify(request, auth_token):
    try:
        profile_obj = EmailVerification.objects.filter(auth_token=auth_token).first()
        if profile_obj:
            if profile_obj.is_verified:
                messages.info(request, 'Your account is already verified.')
                return redirect('signuppage')
            else:
                print(auth_token)
                profile_obj.is_verified = True
                profile_obj.auth_token = ''
                profile_obj.save()
                messages.info(request, 'Your account has been verified.')
                return redirect('signuppage')
        else:
            return redirect('errorpage')
    except Exception as e:
        messages.info(request, e)
        return render(request, 'projectapp/signuppage.html')

def loginUser(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user_obj = User.objects.filter(username=username).first()
        if user_obj is None:
            messages.info(request, 'User not found.')
            return redirect('loginpage')
        else:
            emailverify_obj = EmailVerification.objects.filter(user=user_obj).first()
            user = authenticate(username=username, password=password)
            if user is None:
                messages.info(request, 'Please enter the credentials correctly.')
                return redirect('loginpage')
            else:
                if not emailverify_obj.is_verified:
                    auth_token = str(uuid.uuid4())
                    emailverify_obj.auth_token = auth_token
                    emailverify_obj.save()
                    email_obj = User.objects.get(username=username).username
                    send_mail_after_registration(email_obj, auth_token)
                    messages.info(request, 'Your account is not verified. Please check your mailbox for "Account Verification" mail and click on the link to verify your account. We have sent a new "Account Verification" mail.')
                    return redirect('loginpage')
                else:
                    login(request, user)
                    return redirect('homepage')                
    else:
        return render(request, 'projectapp/loginpg.html')

def logoutUser(request):
    logout(request)
    return redirect('loginpage')

def errorUser(request):
    return render(request, 'projectapp/errorpage.html')

@login_required(login_url="/login")
def home(request):
    company_instance = get_object_or_404(Company, user=request.user)
    company_obj = Company.objects.get(user=request.user)
    forms = Form.objects.filter(reciever=request.user).order_by('-created_at')
    if request.method == 'POST':
        tokenval = request.POST.get('apitoken')
        urlval = request.POST.get('baseurl')
        userval = request.POST.get('userid')
        form = CompanyForm(request.POST, instance=company_instance)
        form_vals = form.save(commit=False)
        form_vals.apitoken = tokenval
        form_vals.baseurl = urlval
        form_vals.userid = userval
        form_vals.save()
        return redirect('homepage')
    context = {'company_obj':company_obj, 'forms':forms}
    return render(request, 'projectapp/homepage.html', context)

def allcontacts(request):
    company_obj = Company.objects.get(user=request.user)
    tokenval = company_obj.apitoken
    urlval = company_obj.baseurl
    url = f'{urlval}persons?api_token={tokenval}'

    # Making the GET request
    response = requests.get(url)

    if response.status_code == 200:
        data = response.json()
        contacts = data.get('data', [])
        for contact in contacts:
            email = contact['email'][0]['value'] if contact['email'] else ''
            phone = contact['phone'][0]['value'] if contact['phone'] else ''
            contact_exist = Contact.objects.filter(email=email).first()
            if contact_exist:
                print('All Contacts Up to Date')
            else:
                Contact.objects.create(
                    owner = request.user,
                    name=contact['name'],
                    email=email,
                    phone=phone,
                )
    else:
        contacts = []
        print('Failed to search:', response.status_code, response.json())
    contactsvar = Contact.objects.filter(owner=request.user)

    contactsv = Contact.objects.filter(owner=request.user)
    if request.method == 'POST':
        contactsv.delete()
        return redirect('contactspage')
    context = {'contactsvar': contactsvar}
    return render(request, 'projectapp/contactspage.html', context)


def alldeals(request):
    company_obj = Company.objects.get(user=request.user)
    tokenval = company_obj.apitoken
    urlval = company_obj.baseurl
    url = f'{urlval}deals?api_token={tokenval}'
    response = requests.get(url)
    if response.status_code == 200:
        data = response.json()
        deals = data.get('data', [])
        for deal in deals:
            person = deal['person_id']['email'][0]['value'] if deal['person_id']['email'] else ''
            title = deal['title']
            deal_exist = Deal.objects.filter(person=person, title=title).first()
            if deal_exist:
                print('All Deals Up to Date')
            else:
                Deal.objects.create(
                    owner = request.user,
                    title=title,
                    value=deal['value'],
                    person=person,
                )
    else:
        deals = []
        print('Failed to search:', response.status_code, response.json())

projectapp/templates/projectapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Api Company</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>
    {% block content %}



    {% endblock %}

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
</body>

</html>

projectapp/templates/projectapp/contactspage.html
{% extends 'projectapp/base.html' %}

{% block content %}
{% include 'projectapp/header.html' %}

<div class="container mt-5">
    <form method="post">
        {% csrf_token %}
        <div class="row">
            <div class="col">
                <button type="submit" class="btn btn-sm btn-info form-control">Refresh</button>
            </div>
        </div>
    </form>
    <div class="row">
        <div class="table-responsive">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th style="min-width: 80px;" scope="col">#</th>
                        <th style="min-width: 150px;" scope="col">Name</th>
                        <th style="min-width: 130px;" scope="col">Email</th>
                        <th style="min-width: 130px;" scope="col">Phone</th>
                    </tr>
                </thead>
                <tbody>
                    {% for contact in contactsvar %}
                    <tr>
                        <th style="white-space: normal;" class="">{{ forloop.counter }}</th>
                        <td style="white-space: normal;" class="">{{ contact.name }}</td>
                        <td style="white-space: normal;" class="">{{ contact.email }}</td>
                        <td style="white-space: normal;" class="">{{ contact.phone }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

{% endblock %}

projectapp/templates/projectapp/dealspage.html
{% extends 'projectapp/base.html' %}

{% block content %}
{% include 'projectapp/header.html' %}

<div class="container mt-5">
    <form method="post">
        {% csrf_token %}
        <div class="row">
            <div class="col">
                <button type="submit" class="btn btn-sm btn-info form-control">Refresh</button>
            </div>
        </div>
    </form>
    <div class="row">
        <div class="table-responsive">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th style="min-width: 80px;" scope="col">#</th>
                        <th style="min-width: 150px;" scope="col">Title</th>
                        <th style="min-width: 130px;" scope="col">Value</th>
                        <th style="min-width: 130px;" scope="col">Client</th>
                    </tr>
                </thead>
                <tbody>
                    {% for deal in dealsvar %}
                    <tr>
                        <th style="white-space: normal;" class="">{{ forloop.counter }}</th>
                        <td style="white-space: normal;" class="">{{ deal.title }}</td>
                        <td style="white-space: normal;" class="">&#8377;{{ deal.value }}</td>
                        <td style="white-space: normal;" class="">{{ deal.person }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

{% endblock %}

projectapp/templates/projectapp/errorpage.html
{% extends 'projectapp/base.html' %}

{% block content %}
{% load static %}

<div class="container mx-auto text-white" id="errorcontainer" style="background-image: url('/static/images/error.jpg');">
    <div class="row text-start p-3" id="errorrow">
        <div class="col-12 col-sm-10 col-md-8 col-lg-6">
            <a href="{% url 'sendmailpage' %}" class="btn btn-info">Back</a>
        </div>
    </div>
</div>

{% endblock %}

projectapp/templates/projectapp/formpage.html
{% extends 'projectapp/base.html' %}

{% block content %}

<h1>Form Page</h1>
<div class="container m-3">
    <form method="post">
        {% csrf_token %}
        {{ company_obj.user }}
        <div class="row mt-3">
            <div class="col-6">
                <label for="id_name" class="mb-2"><b>Name</b></label>
                <input type="text" id="id_name" name="name" class="form-control" required>
            </div>
        </div>
        <div class="row mt-3">
            <div class="col-6">
                <label for="id_email" class="mb-2"><b>Email</b></label>
                <input type="email" id="id_email" name="email" class="form-control" required>
            </div>
        </div>
        <div class="row mt-3">
            <div class="col-6">
                <label for="id_deal" class="mb-2"><b>Deal</b></label>
                <input type="text" id="id_deal" name="deal" class="form-control" required>
            </div>
        </div>
        <div class="row mt-3">
            <div class="col-6">
                <label for="id_note" class="mb-2"><b>Note <small>(Optional)</small></b></label>
                <br>
                <textarea id="id_note" name="note" class="form-control"></textarea>
            </div>
        </div>
        <div class="row mt-3">
            <div class="col-6">
                {% if messages %}
                {% for message in messages %}
                <div class="rounded-1 alert alert-info mt-3">{{ message }}</div>
                {% endfor %}
                {% endif %}
            </div>
        </div>
        <div class="row mt-3">
            <div class="col-6">
                <button type="submit" class="btn btn-outline-success form-control">Submit</button>
            </div>
        </div>
    </form>
</div>

{% endblock %}

projectapp/templates/projectapp/header.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'homepage' %}">Home</a>
        </li>
        <li class="nav-item">
          <a href="{% url 'dealspage' %}" class="nav-link">Deals</a>
        </li>
        <li class="nav-item">
          <a href="{% url 'contactspage' %}" class="nav-link">Contacts</a>
        </li>
        <li class="nav-item">
          <a href="{% url 'testpage' %}" class="nav-link">Test Post Data</a>
        </li>
      </ul>
      <form action="{% url 'logoutpage' %}" class="form-inline my-2 my-lg-0">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Logout</button>
      </form>
    </div>
  </nav>

projectapp/templates/projectapp/homepage.html
{% extends 'projectapp/base.html' %}

{% block content %}
{% include 'projectapp/header.html' %}

<div class="container">
    <form method="post">
        {% csrf_token %}
        <div class="row m-3">
            <div class="col-12 col-sm-3 col-md-2 p-2">
                <label for="id_baseurl" class="mb-1"><b>Base Url :</b></label>
            </div>
            <div class="col-12 col-sm-9 col-md-4 p-2">
                <input type="text" id="id_baseurl" class="form-control" name="baseurl" value="{{ company_obj.baseurl }}" required>
            </div>
            <div class="col-12 col-sm-3 col-md-2 p-2">
                <label for="id_apitoken" class="mb-1"><b>API Token :</b></label>
            </div>
            <div class="col-12 col-sm-9 col-md-4 p-2">
                <input type="text" id="id_apitoken" class="form-control" name="apitoken" value="{{ company_obj.apitoken }}" required>
            </div>
            <div class="col-12 col-sm-3 col-md-2 p-2">
                <label for="id_userid" class="mb-1"><b>User ID :</b></label>
            </div>
            <div class="col-12 col-sm-9 col-md-4 p-2">
                <input type="text" id="id_userid" class="form-control" name="userid" value="{{ company_obj.userid }}" required>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <button type="submit" class="btn btn-sm btn-info form-control">Submit</button>
            </div>
        </div>
    </form>
    <div class="row my-4 text-center p-2">
        <h4>{{ request.user.username }}'s Form Url : <a href="http://127.0.0.1:8000/forms/{{ company_obj.url }}/">Click here</a></h4>
    </div>
    <div class="row">
        <div class="table-responsive">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th style="min-width: 80px;" scope="col">#</th>
                        <th style="min-width: 150px;" scope="col">Name</th>
                        <th style="min-width: 150px;" scope="col">Email</th>
                        <th style="min-width: 130px;" scope="col">Products</th>
                        <th style="min-width: 130px;" scope="col">Notes</th>
                    </tr>
                </thead>
                <tbody>
                    {% for form in forms %}
                    <tr>
                        <th style="white-space: normal;" class="">{{ forloop.counter }}</th>
                        <td style="white-space: normal;" class="">{{ form.name }}</td>
                        <td style="white-space: normal;" class="">{{ form.email }}</td>
                        <td style="white-space: normal;" class="">{{ form.deal }}</td>
                        <td style="white-space: normal;" class="">{{ form.note }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

{% endblock %}

projectapp/templates/projectapp/loginpg.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login to API Company</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/styles1.css' %}">
</head>

<body>
    <div class="contaner">
        <form method="post">
            {% csrf_token %}
            <div class="title logintitle">Login</div>
            <div class="input-box underline">
                <input type="email" placeholder="Enter Your Email" name="username" required>
                <div class="underline"></div>
            </div>
            <div class="input-box">
                <input type="password" placeholder="Enter Your Password" name="password" required>
                <div class="underline"></div>
            </div>
            {% if messages %}
            {% for message in messages %}
            <div class="rounded-1 alert alert-info mt-3">{{ message }}</div>
            {% endfor %}
            {% endif %}
            <div class="input-box button">
                <input type="submit" name="" value="Continue">
            </div>
        </form>
        <div class="option">or Login With Google</div>
        <div class="google">
            <a href="{% url 'social:begin' 'google-oauth2' %}"><i class="fab fa-google"></i>Login With Google</a>
        </div>
        <div class="option">Create an Account? <a href="{% url 'sendmailpage' %}">Sign up</a></div>
    </div>



    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
</body>

</html>

projectapp/templates/projectapp/sendmailpage.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login to API Company</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/styles1.css' %}">
</head>

<body>
    <div class="contaner">
        <form method="post">
            {% csrf_token %}
            <div class="title sendmailtitle">Email Verify</div>
            <div class="option">
                <b>Note : </b>Before you proceed to Signup Page, we need to verify your email. Please go ahead and provide the email you want to Sign Up with.
            </div>
            <div class="input-box underline">
                <input type="email" placeholder="Email" name="username" required>
                <div class="underline"></div>
            </div>
            {% if messages %}
            {% for message in messages %}
            <div class="rounded-1 alert alert-info mt-3">{{ message }}</div>
            {% endfor %}
            {% endif %}
            <div class="input-box button">
                <input type="submit" name="" value="Continue">
            </div>
        </form>
        <div class="option">or Signup With Google</div>
        <div class="google">
            <a href="{% url 'social:begin' 'google-oauth2' %}"><i class="fab fa-google"></i>Signup With Google</a>
        </div>
        <div class="option">Already have an Account? <a href="{% url 'loginpage' %}">Login</a></div>
    </div>



    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
</body>

</html>

projectapp/templates/projectapp/testpage.html
{% extends 'projectapp/base.html' %}

{% block content %}
{% include 'projectapp/header.html' %}

<div class="container">
    <div class="row">
        <div class="table-responsive">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th style="min-width: 80px;" scope="col">#</th>
                        <th style="min-width: 150px;" scope="col">URL</th>
                        <th style="min-width: 100px;" scope="col">Body</th>
                        <th style="min-width: 100px;" scope="col">Params</th>
                    </tr>
                </thead>
                <tbody>
                    {% for post_data in post_datas %}
                    <tr>
                        <th style="white-space: normal;">{{ forloop.counter }}</th>
                        <td style="white-space: normal;">{{ post_data.url }}</td>
                        <td style="white-space: normal;">{{ post_data.data }}</td>
                        <td style="white-space: normal;">{{ post_data.params }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

{% endblock %}